# Generated by Django 4.2.7 on 2023-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.FileField(upload_to='images'),
        ),
    ]
